### ISSUE TITLE
Fails to build on v0.5.9

### ISSUE THREAD

**Issue by mmalecki** [isaacs/node-glob#24]
`npm install` says:

```
> glob@2.0.9 preinstall /Users/maciej/Programowanie/Sources/node-glob
> node-waf clean || true; node-waf configure build

Nothing to clean (project not configured)
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.045s)
Waf: Entering directory `/Users/maciej/Programowanie/Sources/node-glob/build'
[1/8] cxx: deps/glob/glob.c -> build/Release/deps/glob/glob_1.o
[2/8] cxx: deps/fnmatch/fnmatch.c -> build/Release/deps/fnmatch/fnmatch_2.o
[3/8] cxx: src/glob.cc -> build/Release/src/glob_3.o
[4/8] cxx: deps/glob/glob.c -> build/Release/deps/glob/glob_4.o
[5/8] cxx: deps/fnmatch/fnmatch.c -> build/Release/deps/fnmatch/fnmatch_5.o
../src/glob.cc: In function ‘v8::Handle<v8::Value> GlobAsync(const v8::Arguments&)’:
../src/glob.cc:150: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/glob.cc:150: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
Waf: Leaving directory `/Users/maciej/Programowanie/Sources/node-glob/build'
Build failed:  -> task failed (err #1): 
    {task: cxx glob.cc -> glob_3.o}
npm ERR! glob@2.0.9 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! `sh "-c" "node-waf clean || true; node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the glob@2.0.9 preinstall script.
npm ERR! This is most likely a problem with the glob package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || true; node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls glob
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/maciej/Programowanie/Sources/node-glob
npm ERR! node -v v0.5.9
npm ERR! npm -v 1.0.99
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/maciej/Programowanie/Sources/node-glob/npm-debug.log
npm not ok
```
