### ISSUE TITLE
TypeError: glob.sync is not a function using 9.0.1 (worked in 8.1.0)

### ISSUE THREAD

**Issue by elebitzero** [isaacs/node-glob#493]
The OpenRefine pull request broke today when it pulled the latest Glob 9.0.1 version during the build. The last good version was 8.1.0.

See the error message below:
```
Run npm install --save glob && node main/tests/cypress/build-test-matrix.js
...
 + glob@9.0.1
   added 8 packages from 3 contributors and audited 8 packages in 0.866s
```

```
/home/runner/work/OpenRefine/OpenRefine/main/tests/cypress/build-test-matrix.js:58
    const files = glob.sync(`main/tests/cypress/${pattern}`);
                       ^

TypeError: glob.sync is not a function
    at /home/runner/work/OpenRefine/OpenRefine/main/tests/cypress/build-test-matrix.js:58:24
    at Array.forEach (<anonymous>)
    at /home/runner/work/OpenRefine/OpenRefine/main/tests/cypress/build-test-matrix.js:57:15
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/runner/work/OpenRefine/OpenRefine/main/tests/cypress/build-test-matrix.js:56:8)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
Error: Process completed with exit code 1.
```

References:
OpenRefine PR: https://github.com/OpenRefine/OpenRefine/pull/5651
build-test-matrix.js: https://github.com/OpenRefine/OpenRefine/blob/7cacc9117f0f4bcc7792392f2afe0e1f2e712fa2/main/tests/cypress/build-test-matrix.js

**Comment by isaacs** [comment]
This is an intended api change. Please update your code if you pull the semver major, it has breaking changes, that's what semver major means.

**Comment by EHER** [comment]
@elebitzero You can use `globSync` instead.

```js
const { globSync } = require('glob')
const files = globSync(`main/tests/cypress/${pattern}`);
```
More examples [here](https://github.com/isaacs/node-glob#usage).

**Comment by philBrown** [comment]
> This is an intended api change

Yet nothing in the changelog 😢

**Comment by isaacs** [comment]
> Yet nothing in the changelog 😢

Updated changelog. Thanks for the note, that was there in a previous commit, but got lost when I organized it into sections.

**Comment by SPConrad** [comment]
I apologize for opening a very old thread, I'm attempting to update a dependency and it was using an older version of glob. 

How can one check for an error with the new implementation? 
eg: 
old call: 
`glob(`${uploadBundlePath}/**/*`, async (error, files) => {`

new call: 
`const files = globSync(`${uploadBundlePath}/**/*`)`
